apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: afds

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - kafka.yaml
  - redis.yaml
  - flink.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - mcp-server.yaml
  - monitoring.yaml
  - cronjobs.yaml
  - model-api.yaml

commonLabels:
  app.kubernetes.io/part-of: afds
  app.kubernetes.io/managed-by: kustomize
